services:
  - type: web
    name: my-app
    env: python
    buildCommand: |
      # Install backend dependencies
      pip install -r backend/requirements.txt
      # Install frontend dependencies and build
      cd frontend && npm install && npm run build
    startCommand: cd backend && gunicorn app:app
