services:
  - type: web
    name: my-app
    env: python
    buildCommand: |
      # Install frontend dependencies and build
      cd frontend && npm install && npm run build
      # Install backend dependencies
      cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0  # or whichever version you're using
